'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mcia
    Public Property cod_cia As Decimal
    Public Property txt_nom_cia As String
    Public Property cod_tipo_dir As Decimal
    Public Property txt_direccion As String
    Public Property nro_cod_postal As Nullable(Of Decimal)
    Public Property cod_zona_dir As Decimal
    Public Property cod_colonia As Decimal
    Public Property cod_municipio As Decimal
    Public Property cod_dpto As Decimal
    Public Property cod_pais As Decimal
    Public Property cod_tipo_telef As Decimal
    Public Property txt_telefono As String
    Public Property cod_tipo_iva As Decimal
    Public Property nro_nit As String
    Public Property imp_gasto_pilotaje As Decimal
    Public Property cnt_anos_min_ing_vida As Nullable(Of Decimal)
    Public Property cnt_anos_max_ing_vida As Nullable(Of Decimal)
    Public Property cnt_anos_max_perman_vida As Nullable(Of Decimal)
    Public Property txt_nom_redu As String
    Public Property cod_tipo_agente As Nullable(Of Byte)
    Public Property cod_agente As Nullable(Of Integer)
    Public Property tipo_cia As String
    Public Property cod_wins As String
    Public Property cod_ciudad As Nullable(Of Integer)
    Public Property nro_ext As String
    Public Property nro_int As String
    Public Property cod_region As Nullable(Of Decimal)
    Public Property id_persona As Nullable(Of Integer)
    Public Property txt_cheque_a_nom As String
    Public Property sn_inverfas As Nullable(Of Decimal)
    Public Property sn_transferencia As Nullable(Of Decimal)

End Class
